from abc import ABC, abstractmethod
from uuid import UUID
from src.models.entities import SessionEntity, MessageEntity


class ISessionRepository(ABC):
    @abstractmethod
    async def create(self, title: str) -> SessionEntity: ...
    @abstractmethod
    async def get_by_id(self, session_id: UUID) -> SessionEntity | None: ...
    @abstractmethod
    async def list_all(self, limit: int = 20, offset: int = 0) -> list[SessionEntity]: ...
    @abstractmethod
    async def append_message(self, session_id: UUID, role: str, content: str) -> MessageEntity: ...
    @abstractmethod
    async def get_messages(self, session_id: UUID, limit: int | None = None, offset: int = 0) -> list[MessageEntity]: ...
    @abstractmethod
    async def count_messages(self, session_id: UUID) -> int: ...
    @abstractmethod
    async def delete(self, session_id: UUID) -> bool: ...
