from abc import ABC, abstractmethod
from uuid import UUID
from src.models.entities import UserEntity, SessionEntity, MessageEntity, TaskEntity


class IUserRepository(ABC):
    @abstractmethod
    async def get_by_api_key(self, api_key: str) -> UserEntity | None: ...
    @abstractmethod
    async def create(self, username: str, api_key: str) -> UserEntity: ...


class ISessionRepository(ABC):
    @abstractmethod
    async def create(self, user_id: UUID, title: str) -> SessionEntity: ...
    @abstractmethod
    async def get_by_id(self, session_id: UUID, user_id: UUID) -> SessionEntity | None: ...
    @abstractmethod
    async def list_by_user(self, user_id: UUID) -> list[SessionEntity]: ...
    @abstractmethod
    async def append_message(self, session_id: UUID, role: str, content: str) -> MessageEntity: ...
    @abstractmethod
    async def get_messages(self, session_id: UUID) -> list[MessageEntity]: ...
    @abstractmethod
    async def delete(self, session_id: UUID, user_id: UUID) -> bool: ...


class ITaskRepository(ABC):
    @abstractmethod
    async def create(self, task_id: str, user_id: UUID, task_type: str) -> TaskEntity: ...
    @abstractmethod
    async def get_by_id(self, task_id: str, user_id: UUID) -> TaskEntity | None: ...
    @abstractmethod
    async def update_status(self, task_id: str, status: str, result: dict | None = None) -> None: ...